# Generated by Django 3.2.6 on 2021-08-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_register_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
