# Generated by Django 3.2.6 on 2021-09-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210913_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shiphon_brouses',
            new_name='Ladies_wear',
        ),
    ]
