# Generated by Django 3.2.6 on 2021-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_shiphon_brouses_ladies_wear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('BAGS', 'BAGS'), ('SCARVES', 'SCARVES'), ('MEN_WEAR', 'MEN_WEAR'), ('LADIES_WEAR', 'LADIES_WEAR')], max_length=300)),
            ],
        ),
    ]
